import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { AlertTriangle, ArrowLeft, CalendarClock, CheckCircle2, Download, ExternalLink, FileText, Mail, MapPin, MessageCircle, Phone, ShieldAlert, UserRound } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { Avatar, EmptyState, LoadingState, ProgressBar, StatusBadge } from '../components/ui'
import { useInstitution } from '../context/useInstitution'
import { scholarApi } from '../services/api'

export function CandidatePage() {
  const { id = '' } = useParams()
  const [tab, setTab] = useState<'summary' | 'documents' | 'history'>('summary')
  const { institution } = useInstitution()
  const { data: candidate, isLoading } = useQuery({
    queryKey: ['candidate', institution.id, id],
    queryFn: () => scholarApi.getCandidate(id, institution.id),
  })
  if (isLoading) return <LoadingState label="Carregando o dossiê…" />
  if (!candidate) return <EmptyState title="Candidatura indisponível" description="Ela não existe ou não pertence à instituição vinculada ao seu perfil." />
  const money = (value: number) => value.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })
  return <>
    <Link className="back-link" to="/app/inscricoes"><ArrowLeft size={16} />Voltar para inscrições</Link>
    <section className="candidate-header card"><div className="candidate-header__identity"><Avatar initials={candidate.initials} large /><div><span className="eyebrow">CANDIDATURA {candidate.id}</span><h1>{candidate.name}</h1><div className="meta-row"><span><MapPin />{candidate.city}</span><span><CalendarClock />Enviada em {new Date(`${candidate.submittedAt}T12:00`).toLocaleDateString('pt-BR')}</span></div></div></div><div className="candidate-header__actions"><StatusBadge status={candidate.status} /><button className="button button--secondary"><Download size={16} />Baixar relatório</button></div></section>
    <nav className="tabs" aria-label="Seções da candidatura"><button className={tab === 'summary' ? 'active' : ''} onClick={() => setTab('summary')}>Resumo da análise</button><button className={tab === 'documents' ? 'active' : ''} onClick={() => setTab('documents')}>Documentos <span>{candidate.documents.length}</span></button><button className={tab === 'history' ? 'active' : ''} onClick={() => setTab('history')}>Histórico</button></nav>
    {tab === 'summary' && <div className="candidate-layout"><main className="stack-column">
      <section className="card assistant-summary"><div className="card-heading"><div><span className="eyebrow">SÍNTESE ASSISTIDA</span><h2>Resumo para a entrevista</h2></div><span className="ai-label">Organizado automaticamente</span></div><p>{candidate.summary}</p><div className="responsibility-note"><ShieldAlert /><p><strong>Use como ponto de partida.</strong> Confira as evidências originais e converse com a família antes de qualquer decisão.</p></div></section>
      <section className="card"><div className="card-heading"><div><span className="eyebrow">PONTOS PARA CONFERÊNCIA</span><h2>Principais insights</h2></div></div><div className="insights-list">{candidate.insights.map((insight, index) => <div key={insight} className={index === 0 && candidate.pendingCount ? 'warning' : index === 1 && candidate.inconsistentCount ? 'danger' : 'success'}>{index === 0 && candidate.pendingCount ? <AlertTriangle /> : index === 1 && candidate.inconsistentCount ? <ShieldAlert /> : <CheckCircle2 />}<div><strong>{insight}</strong><p>{index === 0 ? 'Confira os documentos marcados abaixo.' : index === 1 ? 'Compare formulário e arquivo original.' : 'Resultado da triagem; sujeito à validação.'}</p></div></div>)}</div></section>
      <section className="card"><div className="card-heading"><div><span className="eyebrow">DOCUMENTAÇÃO</span><h2>Itens que merecem atenção</h2></div><button className="link-button" onClick={() => setTab('documents')}>Ver todos</button></div><div className="document-list">{candidate.documents.filter((document) => document.status !== 'ok' || document.humanReview).slice(0, 5).map((document) => <article key={document.id}><span className="file-icon"><FileText /></span><div><strong>{document.label}</strong><small>{document.relationship} · confiança de {Math.round(document.confidence * 100)}%</small>{document.issue && <p>{document.issue}</p>}</div><StatusBadge status={document.status} /><button className="icon-button" aria-label={`Visualizar ${document.label}`}><ExternalLink /></button></article>)}</div></section>
    </main><aside className="stack-column">
      <section className="card profile-card"><div className="card-heading"><div><span className="eyebrow">DADOS DE CONTATO</span><h2>Informações principais</h2></div></div><dl><div><dt><Mail />E-mail</dt><dd>{candidate.email}</dd></div><div><dt><Phone />Telefone</dt><dd>{candidate.phone}</dd></div><div><dt><UserRound />Idade</dt><dd>{candidate.age} anos</dd></div></dl><button className="button button--soft button--full"><MessageCircle />Entrar em contato</button></section>
      <section className="card"><span className="eyebrow">CONTEXTO SOCIOECONÔMICO</span><div className="finance-grid"><div><small>Renda familiar</small><strong>{money(candidate.monthlyIncome)}</strong></div><div><small>Renda per capita</small><strong>{money(candidate.perCapitaIncome)}</strong></div><div><small>Núcleo familiar</small><strong>{candidate.familyMembers} pessoas</strong></div><div><small>Documentação</small><strong>{candidate.progress}% completa</strong></div></div><ProgressBar value={candidate.progress} /></section>
    </aside></div>}
    {tab === 'documents' && <section className="card"><div className="card-heading"><div><span className="eyebrow">DOSSÊ DIGITAL</span><h2>Todos os documentos</h2></div><ProgressBar value={candidate.progress} /></div><div className="document-list document-list--all">{candidate.documents.map((document) => <article key={document.id}><span className="file-icon"><FileText /></span><div><strong>{document.label}</strong><small>{document.category} · {document.relationship} · {document.required}</small>{document.issue && <p>{document.issue}</p>}</div><span className="confidence">{Math.round(document.confidence * 100)}%<small>confiança</small></span><StatusBadge status={document.status} /><button className="icon-button" aria-label={`Visualizar ${document.label}`}><ExternalLink /></button></article>)}</div></section>}
    {tab === 'history' && <section className="card"><div className="card-heading"><div><span className="eyebrow">RASTREABILIDADE</span><h2>Histórico da candidatura</h2></div></div><div className="history-list"><div><i /><strong>Candidatura organizada para análise</strong><span>Hoje, 09:40 · ScholarOps</span></div><div><i /><strong>Extração de documentos concluída</strong><span>Ontem, 18:12 · Processamento automático</span></div><div><i /><strong>Documentos enviados pela família</strong><span>{new Date(`${candidate.submittedAt}T12:00`).toLocaleDateString('pt-BR')} · Portal da candidatura</span></div></div></section>}
  </>
}
